name: JWT
dbless_compatible: partially
dbless_explanation: |
  Consumers and JWT secrets can be created with declarative configuration.

  Admin API endpoints that do POST, PUT, PATCH, or DELETE on secrets are not available on DB-less mode.
extra: |
  <div class="alert alert-warning">
      <center>The option <code>config.run_on_preflight</code> is only available from version <code>0.11.1</code> and later.</center>
  </div>
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - authentication
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Verify and authenticate JSON Web Tokens
description: |
  Verify requests containing HS256 or RS256 signed JSON Web Tokens (as specified
  in [RFC 7519](https://tools.ietf.org/html/rfc7519)). Each of your Consumers
  will have JWT credentials (public and secret keys), which must be used to sign
  their JWTs. A token can then be passed through:

  - a query string parameter
  - a cookie
  - HTTP request headers

  Kong will either proxy the request to your Upstream services if the token's
  signature is verified, or discard the request if not. Kong can also perform
  verifications on some of the registered claims of RFC 7519 (exp and nbf).
