dist: xenial
sudo: false

language: generic
notifications:
  email: false

before_install:
  - docker-compose build
  - touch Gemfile.lock
  - mkdir node_modules
  - chmod -R 777 .
script:
  - make check-links