ubuntu:
  image: "ubuntu:jammy"
  setup:
    - apt-get update -y
    - apt-get install -y curl gpg sudo lsb-release
    - useradd tester -m -p password
    - usermod -aG sudo tester
    - "echo 'ALL            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/tester"
debian:
  image: "debian:11"
  setup:
    - apt-get update -y
    - apt-get install -y curl gpg sudo lsb-release
    - useradd tester -m -p password
    - usermod -aG sudo tester
    - "echo 'ALL            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/tester"
rhel:
  image: "registry.access.redhat.com/ubi9/ubi-init:latest"
  setup:
    - yum install -y gpg sudo
    - useradd tester -m -p password
    - "echo 'ALL            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/tester"
amazon-linux:
  image: "amazonlinux:2"
  setup:
    - yum install -y curl gpg sudo shadow-utils util-linux
    - useradd tester -m -p password
    - "echo 'ALL            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/tester"
centos:
  image: "centos:centos7"
  setup:
    - yum install -y curl gpg sudo
    - useradd tester -m -p password
    - "echo 'ALL            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/tester"
