name: Auto Close Org Issues
on:
  issues:
    types: [opened]

jobs:
  auto-close-org-issues:
    name: Auto Close Org Issues
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate app token
        id: generate-app-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ vars.GH_APP_KONG_DOCS_APP_ID }}
          private_key: ${{ secrets.GH_APP_KONG_DOCS_PRIVATE_KEY }}
      - name: Auto Close Org Issues
        uses: mheap/auto-close-org-issues-action@v1
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          org: Kong
          message: |
            Thanks for raising an issue! We track issues raised by Kong employees in Jira.

            Please submit your request in the DOCU project and we'll get it prioritized.
          keep_open: "Kubernetes Team"
