name: Build and Test
on:
  pull_request:
    types: [synchronize, ready_for_review]
jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Clean environment and files
      run: make clean
    - name: Build docker-compose stack
      run: docker-compose build
    - name: Create dist folder
      run: mkdir dist
    - name: Set permissions
      run: sudo chmod -R 777 .
    - name: Run tests
      run: make docker-test
    - name: Check links
      run: make check-links
