name: Generate Changelog

on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.PAT }}
      - name: Run changelog script
        working-directory: tools/changelog-generator
        run: |
          npm ci
          node changelog.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          title: Automated Changelog update [skip-ci]
          body: |
            This is a scheduled pull request to update the changelog.
          labels: skip-changelog,review:copyedit
          base: main
          branch: automated-changelog-update
          token: ${{ secrets.PAT }}
          committer: kong-docs[bot] <team-docs@konghq.com>
          author: kong-docs[bot] <team-docs@konghq.com>
          delete-branch: true
          commit-message: "Automated changelog update"